// Writes .env.local from the running local Supabase stack so dev and tests always
// target it. Next.js loads .env.local ahead of .env (the hosted keys), so a missing
// or stale local stack fails loudly here instead of silently hitting production.
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

let out;
try {
  out = execSync("npx --no-install supabase status -o env", {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    shell: true,
  });
} catch (err) {
  const stderr = err && err.stderr ? String(err.stderr).trim().split("\n").slice(-3).join("\n") : "";
  console.error("[local-env] local Supabase stack is not running. Start Docker, then `npx supabase start`.");
  if (stderr) console.error(stderr);
  process.exit(1);
}

const get = (key) => {
  const m = out.match(new RegExp(`^${key}="?([^"\\r\\n]+)"?$`, "m"));
  return m ? m[1] : undefined;
};

const url = get("API_URL");
const anon = get("ANON_KEY") ?? get("PUBLISHABLE_KEY");
const service = get("SERVICE_ROLE_KEY") ?? get("SECRET_KEY");
const db = get("DB_URL");
const mail = get("MAILPIT_URL") ?? get("INBUCKET_URL");

const missing = Object.entries({ API_URL: url, ANON_KEY: anon, SERVICE_ROLE_KEY: service, DB_URL: db, MAILPIT_URL: mail })
  .filter(([, v]) => !v)
  .map(([k]) => k);
if (missing.length) {
  console.error(`[local-env] supabase status did not report: ${missing.join(", ")}`);
  process.exit(1);
}

const host = new URL(url).hostname;
if (host !== "127.0.0.1" && host !== "localhost") {
  console.error(`[local-env] refusing to write .env.local for a non-local API_URL host: ${host}`);
  process.exit(1);
}

// F13: the cron route's bearer for the local stack. Derived from the stack's own key so
// it is stable across rewrites (Playwright reads .env.local before the dev server's
// predev rewrites it) and never a literal in source. Local only; production sets its own.
const cronSecret = createHash("sha256").update(`${service}:reminders`).digest("hex");

const body = [
  "# Generated by scripts/local-env.mjs from `supabase status`. Do not edit; not committed.",
  `NEXT_PUBLIC_SUPABASE_URL=${url}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}`,
  `SUPABASE_SERVICE_ROLE_KEY=${service}`,
  `LOCAL_DATABASE_URL=${db}`,
  `LOCAL_MAILPIT_URL=${mail}`,
  `CRON_SECRET=${cronSecret}`,
  "SUPABASE_TARGET=local",
  "",
].join("\n");

const target = resolve(process.cwd(), ".env.local");
writeFileSync(target, body, { encoding: "utf8" });
console.log(`[local-env] wrote .env.local for ${url}`);
